export default {
  locationon: require("../assets/images/location.png"),
  expandmore: require("../assets/images/expandmore.png"),
  home: require("../assets/images/icon1.png"),
  restaurant: require("../assets/images/icon4.png"),
  cart: require("../assets/images/icon2.png"),
  calender: require("../assets/images/icon3.png"),
  menu: require("../assets/images/icon5.png"),
  search: require("../assets/images/search.png"),
  bullet: require("../assets/images/bullet.png"),
  CNN: require("../assets/images/CNN.png"),
  Starmovies: require("../assets/images/starmovies.png"),
  StarSports: require("../assets/images/startsports.png"),
  discovery: require("../assets/images/discovery.png"),
  tv: require("../assets/images/tv.png"),
  church: require("../assets/images/church.png"),
  radio: require("../assets/images/radio.png"),
  OTT1: require("../assets/images/hdimage1.jpg"),
  OTT2: require("../assets/images/hdimage2.jpg"),
  OTT3: require("../assets/images/hdimage3.jpg"),
  OTT4: require("../assets/images/hdimage4.jpg"),
  image2: require("../assets/images/image2.jpg"),
  image3: require("../assets/images/images3.jpg"),
  image4: require("../assets/images/image4.jpg"),
  calender2: require("../assets/images/calender2.png"),
};
